

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        gnat_version: [10.2.1, 11.3.1]
        gprbuild_version: [21.0.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v1
        with:
          toolchain: gprbuild=${{ matrix.gprbuild_version }} gnat_native=${{ matrix.gnat_version }}
      - run: alr build
      - run: cd example && alr build
